apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: goods
  name: goods
spec:
  ports:
  - name: "8890"
    port: 8890
    targetPort: 8890
  selector:
    io.kompose.service: goods
status:
  loadBalancer: {}
